In [1]:
!pip install numpy pandas matplotlib

Note: you may need to restart the kernel to use updated packages.


# To know about the function ( shift+tab )

In [2]:
import numpy as np  

In [5]:
a=np.array([1,2,3,4,5,6])

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.size

6

In [9]:
a.dtype

dtype('int32')

In [10]:
a.itemsize

4

In [12]:
a.dtype.name

'int32'

In [13]:
a.ndim

1

# Accessing data from array

In [14]:
a[0]

1

In [15]:
a[-1]

6

In [16]:
a[2]

3

In [17]:
a[:3]

array([1, 2, 3])

In [18]:
a[:]

array([1, 2, 3, 4, 5, 6])

# comparision between array and list

In [19]:
l1=[1,2,3,4,5,6,7,8]

In [20]:
type(l1)

list

In [ ]:
sys.getsizeof(8)

In [21]:
a=np.array([1,2,3,4,5,6,7,8])

In [22]:
type(a)

numpy.ndarray

In [23]:
import sys

In [27]:
sys.getsizeof(3)

28

In [28]:
a.itemsize

4

# size

In [29]:
sys.getsizeof(2)*len(l1)

224

In [33]:
a.itemsize*len(a)

32

# time

In [1]:
import time

In [2]:
n=10000000

In [3]:
l1=range(n)
l2=range(n)

In [4]:
s=time.time()

In [16]:
add=[(x+y) for x,y in zip(l1,l2)]

In [6]:
print((time.time()-s)*1000)

3895.662307739258


In [7]:
import numpy as np

In [8]:
a1=np.arange(n)
a2=np.arange(n)

In [9]:
s1=time.time()

In [10]:
add1=a1+a2

In [11]:
print((time.time()-s1)*1000)

1413.9196872711182


# creating array in different ways

# 1D array

In [3]:
import numpy as np

In [5]:
a1=np.array([1,2,3,4,5],dtype=float)

In [6]:
a1

array([1., 2., 3., 4., 5.])

In [7]:
a1.dtype

dtype('float64')

In [8]:
a1=np.array([1,2,3,4,5],dtype=complex)

In [9]:
a1

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [10]:
a2=np.arange(2,10,2)

In [11]:
a2

array([2, 4, 6, 8])

In [12]:
a2=np.arange(5)

In [13]:
a2

array([0, 1, 2, 3, 4])

In [16]:
a2=np.arange(0,6,0.5)

In [17]:
a2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [20]:
a3=np.linspace(2,10,15)

In [21]:
a3

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

In [23]:
a3[-1]

10.0

In [24]:
a3=np.linspace(1,1.8,20)

In [25]:
a3

array([1.        , 1.04210526, 1.08421053, 1.12631579, 1.16842105,
       1.21052632, 1.25263158, 1.29473684, 1.33684211, 1.37894737,
       1.42105263, 1.46315789, 1.50526316, 1.54736842, 1.58947368,
       1.63157895, 1.67368421, 1.71578947, 1.75789474, 1.8       ])

In [26]:
a4=np.zeros(5)

In [27]:
a4

array([0., 0., 0., 0., 0.])

In [28]:
a5=np.ones(7)

In [29]:
a5

array([1., 1., 1., 1., 1., 1., 1.])

# 2D array

In [31]:
a6=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [32]:
a6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
a6.ndim

2

In [34]:
a6.dtype

dtype('int32')

In [35]:
a6.itemsize

4

In [36]:
a6.shape

(2, 5)

In [37]:
a6[0]

array([1, 2, 3, 4, 5])

In [39]:
a6[1]

array([ 6,  7,  8,  9, 10])

In [40]:
a6[0][0]

1

In [41]:
a6[1][2]

8

In [43]:
a7=np.arange(15).reshape(3,5)
a7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
a7=np.arange(15).reshape(5,3)
a7

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [45]:
a7[0]

array([0, 1, 2])

In [46]:
a7[1]

array([3, 4, 5])

In [16]:
a8=np.arange(20).reshape(4,5)
a8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
a8[1,::4]

array([5, 9])

In [28]:
a8[1:4,::4]

array([[ 5,  9],
       [10, 14],
       [15, 19]])

In [42]:
a8[1:4:2,::4]

array([[ 5,  9],
       [15, 19]])

In [5]:
np.arange(20).reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [7]:
np.linspace(2,10,6).reshape(3,2)

array([[ 2. ,  3.6],
       [ 5.2,  6.8],
       [ 8.4, 10. ]])

In [8]:
a8[2]

array([10, 11, 12, 13, 14])

In [11]:
a8[2][:3]

array([10, 11, 12])

In [12]:
a8[2,:3]

array([10, 11, 12])

In [13]:
a8[1, 1:4]


array([6, 7, 8])

In [32]:
a8[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [36]:
a8[1:3, 1:3]


array([[ 6,  7],
       [11, 12]])

In [16]:
a8[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [19]:
a8[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [26]:
a8[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [27]:
a8[1::2, 0::4]

array([[ 5,  9],
       [15, 19]])

In [28]:
a8[1:4,0:5:4]

array([[ 5,  9],
       [10, 14],
       [15, 19]])

In [29]:
a8[1::2, 1::4]

array([[ 6],
       [16]])

In [30]:
a8[1::2, 1::4]

array([[ 6],
       [16]])

In [31]:
a8[1:4:2,::4]

array([[ 5,  9],
       [15, 19]])

In [33]:
a8[1][::4],[2][::4]

(array([5, 9]), [2])

In [34]:
a8[1:4:2,0:5:4]

array([[ 5,  9],
       [15, 19]])

In [35]:
a8[1:4:2, 0::4]

array([[ 5,  9],
       [15, 19]])

In [44]:
a8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
a8.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [47]:
a8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
a8.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [49]:
a8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [50]:
a8.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

# 3D array

In [3]:
d3=np.arange(30).reshape(3,10)
d3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [12]:
a=np.arange(30).reshape(2,5,3)

In [37]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [ ]:
# Exception trail exemple :

In [10]:
a=np.arange(30).reshape(3,2,5)

In [11]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [14]:
a[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [59]:
a[1]

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [62]:
a[0][0][2]

2

In [63]:
a[0][2]

array([6, 7, 8])

In [64]:
a[0][2][::]

array([6, 7, 8])

In [40]:
a[1,3,::]

array([24, 25, 26])

In [65]:
a[0,2]

array([6, 7, 8])

# operations of array

In [66]:
a=np.arange(10).reshape(2,5)

In [67]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a.min()

0

In [70]:
a.max()

9

In [71]:
a.sum()

45

In [73]:
a.sum(axis=1)

array([10, 35])

In [74]:
a.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [75]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [92]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [77]:
a

array([[1, 2],
       [3, 4]])

In [78]:
b

array([[5, 6],
       [7, 8]])

In [79]:
a+b

array([[ 6,  8],
       [10, 12]])

In [80]:
a-b

array([[-4, -4],
       [-4, -4]])

In [81]:
a*b

array([[ 5, 12],
       [21, 32]])

In [82]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [83]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [84]:
a@b

array([[19, 22],
       [43, 50]])

In [85]:
a

array([[1, 2],
       [3, 4]])

In [87]:
for i in a:
    print(i*6)

[ 6 12]
[18 24]


# stacking

In [93]:
a

array([[1, 2],
       [3, 4]])

In [94]:
b

array([[5, 6],
       [7, 8]])

In [96]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [97]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# splitting

In [103]:
a=np.arange(30).reshape(2,15)

In [104]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [105]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [101]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [48]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [52]:
b=np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [53]:
np.hstack((a,b))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [54]:
np.vstack((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
# IF

In [55]:
b=np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# Must have Same Shape Or Array Dimensions to Concatenate.

In [56]:
np.vstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3